global using Azure;
global using Azure.AI.DocumentIntelligence;
global using CsvHelper;
global using CsvHelper.Configuration;
global using CsvHelper.Configuration.Attributes;
global using iText.Kernel.Pdf;
global using Markdig;
global using Markdig.Extensions.Tables;
global using Markdig.Syntax;
global using Markdig.Syntax.Inlines;
global using System.Text;
global using Path = System.IO.Path;
global using System.Globalization;
